// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteObjectFile(arg1:string):Promise<void>;

export function GetAllObjectTypeFiles():Promise<Array<string>>;

export function GetAllObjects():Promise<Array<string>>;

export function GetChat(arg1:string):Promise<string>;

export function GetSummary(arg1:string):Promise<string>;

export function ReadObjectFile(arg1:string):Promise<string>;

export function ReadObjectTypeFile(arg1:string):Promise<string>;

export function ReadStateFile():Promise<string>;

export function WriteObjectFile(arg1:string,arg2:string):Promise<void>;

export function WriteObjectTypeFile(arg1:string,arg2:string):Promise<void>;

export function WriteStateFile(arg1:string):Promise<void>;
