// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateObject(arg1) {
  return window['go']['main']['App']['CreateObject'](arg1);
}

export function CreateObjectType(arg1) {
  return window['go']['main']['App']['CreateObjectType'](arg1);
}

export function DeleteObjectFile(arg1) {
  return window['go']['main']['App']['DeleteObjectFile'](arg1);
}

export function DeleteObjectType(arg1) {
  return window['go']['main']['App']['DeleteObjectType'](arg1);
}

export function GetAllObjectTypeFiles() {
  return window['go']['main']['App']['GetAllObjectTypeFiles']();
}

export function GetAllObjects() {
  return window['go']['main']['App']['GetAllObjects']();
}

export function GetChat(arg1) {
  return window['go']['main']['App']['GetChat'](arg1);
}

export function GetObject(arg1) {
  return window['go']['main']['App']['GetObject'](arg1);
}

export function GetRecentObjectsofType(arg1) {
  return window['go']['main']['App']['GetRecentObjectsofType'](arg1);
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function ReadObjectFile(arg1) {
  return window['go']['main']['App']['ReadObjectFile'](arg1);
}

export function ReadObjectTypeFile(arg1) {
  return window['go']['main']['App']['ReadObjectTypeFile'](arg1);
}

export function ReadStateFile() {
  return window['go']['main']['App']['ReadStateFile']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function UpdateObject(arg1) {
  return window['go']['main']['App']['UpdateObject'](arg1);
}

export function WriteObjectFile(arg1, arg2) {
  return window['go']['main']['App']['WriteObjectFile'](arg1, arg2);
}

export function WriteObjectTypeFile(arg1, arg2) {
  return window['go']['main']['App']['WriteObjectTypeFile'](arg1, arg2);
}

export function WriteStateFile(arg1) {
  return window['go']['main']['App']['WriteStateFile'](arg1);
}
